version: '3.8'

services:
  soapui:
    privileged: true
    network_mode: 'host'
    build:
      context: .
      dockerfile: ${BUILD_FILE}
      args:
        DEBIAN_VERSION: ${DEBIAN_VERSION}
        SOAPUI_VERSION: ${SOAPUI_VERSION}
    image: ${IMAGE_NAME}:${SOAPUI_VERSION}
    environment:
    - DISPLAY
    volumes:
    - ./docker-entrypoint.sh:/usr/local/SmartBear/SoapUI-${SOAPUI_VERSION}/bin/docker-entrypoint.sh:ro
    - .docker/soapui/config:/home/app/.soapuios/config
    - .docker/soapui/files:/home/app/files
